### ISSUE TITLE
Question regarding "train_result.out"

### ISSUE THREAD

**Issue by modanesh** [kitsook/face#1]
Hi,
I was wondering what does train_result.out contain? 
And how it is used for training?

Thanks.

**Comment by kitsook** [comment]
It stores the training result.  After you train the face recognizer with images, you can use the trained model to try to recognize/predict faces in new images.  But since the training part is computation intensive, you don't want to train the recognizer every time you start the program, hence it is better to store the training result and load it later.

What exactly is stored in the file will depend on the recognizer you use.

You may also want to read some materials on machine learning on how the training and prediction works.

**Comment by modanesh** [comment]
> What exactly is stored in the file will depend on the recognizer you use.

If I use the eigenfaces recognizer, what will be stored in the file? How about fisherfaces?

**Comment by adarshraj3369** [comment]
cv2.error: OpenCV(4.1.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'


what is this error?
